M48
; DRILL file {KiCad 7.0.2-0} date 2025 January 08, Wednesday 15:26:20
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-08T15:26:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.1811Y-3.3465
T2
X5.6693Y-3.9951
X5.6693Y-4.0951
X5.6693Y-4.1951
T0
M30
